# Generated by Django 4.0.1 on 2022-02-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hablidades', models.CharField(max_length=50, verbose_name='habilidades')),
            ],
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Mi Empleado', 'verbose_name_plural': 'Mis Empleados'},
        ),
    ]
